---
title: "hw5"
output: html_document
---
###5.1

```{r setup, include=FALSE}
chairs <- read.csv("https://raw.githubusercontent.com/agricolamz/2019_data_analysis_for_linguists/master/data/students/amikoz/hw5_CA_MCA/hw5_chairs.csv")

MCA <- MASS::mca(chairs[,-1])

chairs <- cbind(chairs, MCA$rs)
variables <- as_data_frame(MCA$cs)
variables$var_names <- rownames(MCA$cs)
chairs %>% 
  ggplot(aes(`1`, `2`))+
  geom_point(aes(color = Category))+
  stat_ellipse(aes(color = Category))+
  geom_text(data = variables, aes(`1`, `2`, label = var_names), size=3)+
  theme_bw()+
  scale_x_continuous(limits = c(-0.015, 0.02))
```
###5.2

```{r}
Stuhl и Sessel различают с помощью большого количества признаков: Function (кресло - отдых, стул - все остальные функции), MaterialSeat, Soft (кресло - да, стул - нет), Roll (кресло - нет, стул - да), AddFunctions и тд. 

```

###5.3

```{r pressure, echo=FALSE}
colreg <- read.csv("https://raw.githubusercontent.com/agricolamz/2019_data_analysis_for_linguists/master/data/students/amikoz/hw5_CA_MCA/hw5_colreg.csv")

rownames(colreg) <- colreg$colors
ca <- ca(colreg[-5])

colreg_col <- data.frame(ca$colcoord)
colreg_col$rows <- rownames(ca$colcoord)

colreg_row <- data.frame(ca$rowcoord)
colreg_row$rows <- rownames(ca$rowcoord)

colreg_col %>% 
  ggplot(aes(Dim1, Dim2, label = rows))+
  geom_text(color = "blue")+
  geom_text(data = colreg_row, color = "red")+
  theme_bw()+
  labs(x = "Dim1",
       y = "Dim2")
```

###5.4 

```{r}
Согласно графику, черный и белый цвета часто используют в разговорной речи, белый также популрен в академической сфере. Возможно, это потому что часто людей делят по цвету кожи - "белые" и "черные".
В художественной литературе используются цвета: коричневый, фиолетовый, розовый, голубой, желтый.
В прессе: зеленый, оранжевый, красный.
```

